version: '3.8'

services:
  backend:
    extends:
      file: ./backend/docker-compose.yml
      service: web

  celery_worker:
    extends:
      file: ./backend/docker-compose.yml
      service: celery_worker

  redis:
    extends:
      file: ./backend/docker-compose.yml
      service: redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    name: migibot_network
    driver: bridge
volumes:
  redis_data:
    driver: local
