services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
      - /app/.venv
      - /app/__pycache__
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: "no"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://172.16.20.40:8000
    depends_on:
      - backend
    restart: "no"