version: "3.8"

services:
  backend:
    extends:
      file: ./backend/docker-compose.yml
      service: web
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama

  celery_worker:
    extends:
      file: ./backend/docker-compose.yml
      service: celery_worker
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  redis:
    extends:
      file: ./backend/docker-compose.yml
      service: redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    name: migibot_network
    driver: bridge

volumes:
  redis_data:
    driver: local
  ollama_data:
    driver: local
