celery:
  broker_url: ${CELERY_BROKER_URL:-redis://redis:6379/0}
  result_backend: ${CELERY_RESULT_BACKEND:-redis://redis:6379/1}
chunking:
  chunk_overlap: 200
  chunk_size: 512
embedding:
  additional_params: {}
  device: cpu
  model_name: BAAI/bge-base-en-v1.5
  provider: huggingface
features:
  enable_parsers: true
llm:
  additional_params: {}
  base_url: http://ollama:11434
  max_tokens: null
  model_name: llama3.1:8b
  provider: ollama
  streaming: true
  temperature: 0.0
paths:
  base_dir: null
  faiss_index_dir: vector_stores/faiss_index
  markdown_dir: markdown
  vector_store_dir: vector_stores
project:
  api_version: /api/v1
  name: Simba
  version: 1.0.0
retrieval:
  k: 5
vector_store:
  additional_params: {}
  collection_name: migi_collection
  provider: faiss
