version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./uploads:/app/uploads:rw
      - ./markdown:/app/markdown:rw
      - ./vector_stores:/app/vector_stores:rw
    depends_on:
      - redis
      - celery_worker
    networks:
      - app_network
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - PYTHONPATH=/app
      - C_FORCE_ROOT=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./uploads:/app/uploads:rw
      - ./markdown:/app/markdown:rw
      - ./vector_stores:/app/vector_stores:rw
    depends_on:
      - redis
    networks:
      - app_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app_network
    volumes:
      - redis_data:/data
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  redis_data: 