version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./uploads:/app/uploads:rw
      - ./markdown:/app/markdown:rw
      - ./vector_stores:/app/vector_stores:rw
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    mem_limit: 1g
    cpus: 0.5
    runtime: nvidia

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A tasks.parsing_tasks worker --loglevel=info
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./uploads:/app/uploads:rw
      - ./markdown:/app/markdown:rw
      - ./vector_stores:/app/vector_stores:rw
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app_network
    restart: on-failure
    security_opt:
      - no-new-privileges
    mem_limit: 2g
    cpus: 1
    runtime: nvidia

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app_network
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    mem_limit: 512m
    cpus: 0.3

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
    name: simba_redis_data
    driver: local 
